version: '3.3'

services:
  sender:
    ports:
      - 8060:8060
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - PG_HOST=${PG_HOST}
      - PG_USERNAME=${PG_USERNAME}
      - PG_PASSWORD=${PG_PASSWORD}
