apiVersion: v1
kind: Service
metadata:
  name: pgservice
  namespace: blusalt
  labels:
    app: drone-db
spec:
  selector:
    app: drone-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
