apiVersion: v1
kind: Service
metadata:
  name: droneservice
  namespace: blusalt
  labels:
    app: drone-service
spec:
  selector:
    app: drone-service
  ports:
  - port: 8060
    targetPort: 8060
