apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "drone-service.configmap" . }}
data:
  db_port: {{ .Values.postgresql.global.postgresql.service.ports.postgresql | quote}}
  db_name: {{ .Values.postgresql.global.postgresql.auth.database | quote }}