apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "drone-service.fullname" . }}
  labels:
    {{- include "drone-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "drone-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "drone-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "drone-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: {{ .Values.initial.DelaySeconds | int}}
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds:  {{ .Values.initial.DelaySeconds | int}}  
            
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "drone-service.secret" . }}
                  key: db-user
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ include "drone-service.secret" . }}
                  key: db-host
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "drone-service.secret" . }}
                  key: db-password
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "drone-service.configmap" . }}
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "drone-service.configmap" . }}
                  key: db_name
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
