apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone-service.secret" . }}
type: {{ .Values.secret.type }}
data:
  db-user: {{ .Values.secret.dbUser | b64enc }}
  db-host: {{ .Values.secret.dbHost | b64enc }}
  db-password: {{ .Values.secret.dbPassword | b64enc }}
  