apiVersion: v1
kind: Secret
metadata:
  name: {{ include "drone-service.secret" . }}
type: {{ .Values.secret.type }}
data:
  db-user: {{ .Values.postgresql.global.postgresql.auth.username | b64enc }}
  db-host: {{ include "pg.fullname" . | trimSuffix "\n" | b64enc }}
  db-password: {{ .Values.postgresql.global.postgresql.auth.password | b64enc }}
  