apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: blusalt
type: Opaque
data:
  db-user: cm9vdA==
  db-password: cm9vdA==
  db-host: cGdzZXJ2aWNl



# note on production env you won't want to commit this fil to git should be use locally.. as it exposes our services
